description = "Inject userscripts using mitmproxy."
flag_inline = "--inline"
help_inline = "Always insert userscripts inline, never linked"
flag_verbose = "--verbose"
help_verbose = "Insert an HTML comment with a list of injected userscripts"
