#!/usr/bin/env bash

export MYPYPATH=/usr/local/lib/python3.6/dist-packages/

cd src
mypy *.py --ignore-missing-imports --follow-imports skip
mypy modules/*.py --ignore-missing-imports --follow-imports skip
