#!/usr/bin/env bash

set -e

export MYPYPATH=/usr/local/lib/python3.6/dist-packages/

mypy src/*.py --ignore-missing-imports --check-untyped-defs --follow-imports skip
mypy src/modules/*.py --ignore-missing-imports --check-untyped-defs --follow-imports skip
