VERSION_PREFIX: str = "v"
APP_NAME: str = "Userscript Proxy"
VERSION: str = "0.11.0"
ATTRIBUTE_UP_VERSION: str = "data-userscript-proxy-version"
DEFAULT_PORT: int = 8080
DEFAULT_ROOT_DIR: str = "/usr/share/userscript-proxy/"
DEFAULT_RULES_DIR: str = DEFAULT_ROOT_DIR + "rules"
DEFAULT_USERSCRIPTS_DIR: str = DEFAULT_ROOT_DIR + "userscripts"
DEFAULT_QUERY_PARAM_TO_DISABLE: str = "nouserscripts"
