name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      - name: Install CLI tool
        run: |
          npm install --global .
      - name: Bootstrap userscript
        working-directory: ${{ runner.temp }}
        run: |
          mkdir bootstrapped-userscript
          cd $_
          userscripter init
          npm install
          npm run build
